id: P003072
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-17 10:38:38.525676
source_metadata:
  id: bdr:W1KG1574
  title: 'གསང་སྔགས་རྒྱུད་སྡེ་རྒྱ་མཚོའི་རས་བྲིས་བདེ་སྟོང་ཟབ་གསལ། '
  author: ''
  volumes:
    e64419b2099f4aedb1f63570bbea4c68:
      image_group_id: I1KG1577
      title: ''
      volume_number: 1
      total_pages: 142
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
